### ISSUE TITLE
Export of VBA

### ISSUE THREAD

**Issue by Greedquest** [mbarnesatbbs/VBA-MicrosoftGraph#1]
Hi 

Thanks for this amazing work. 

I would really appreciate if you were able to provide an unzipped export of the VBA alongside everything else in this repo. It is convenient to download a zip but you can actually do that from GitHub already (code->download zip) 

It's really useful to be able to view the source code on mobile without having to download things

Export all modules is provided by Rubberduck vba

**Comment by mbarnesatbbs** [comment]
Good idea.  I tried to follow the folder arrangement from the source on this and since this example is in Access, added a Forms directory for those exports.

**Comment by Greedquest** [comment]
Fab thanks
